services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - VLLM_CPU_KVCACHE_SPACE=8

  dozzle:
    image: amir20/dozzle
    container_name: fastapi_logs
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"